### ISSUE TITLE
06 - 04 - Roshambo!

### ISSUE THREAD

**Issue by AbtaheeAli** [AbtaheeAli/assignments#24]
Create a Roshambo (Rock-Paper-Scissors) game.

## Objectives

- Work with JavaScript and the DOM
- Practice conditional logic

### Background

See the Wikipedia page about
[Rock, Paper, Scissors](https://en.wikipedia.org/wiki/Rock%E2%80%93paper%E2%80%93scissors)

### How to get started

- Get familiar with rock, paper, scissors if you haven't played before (or in a while)
- Draw out on paper/whiteboard/computer the rough design of your application
  - See _Explorer Mode_ for the UI requirements
- Start by placing all the HTML elements on the page
- Style the user interface
- Write out in English, ALL the steps the application needs to take
  - For example "When user one clicks on Rock, remember that user one chooses
    Rock"

#### Part 1

> NOTE: Complete part 1 before moving on to part 2

- [x] There should be three buttons for Player One: Rock, Paper, Scissors
- [x] There should be three buttons for Player Two: Rock, Paper, Scissors
- [x] Player One should be able to select their throw
- [x] Player Two should be able to select their throw
- [x] After both players make their selection, I should be told who won and the game should be over.

#### Part 2

- [x] You have heard about _Rock, Paper, Scissors_, but have you tried
      [_Rock, Paper, Scissors, Lizard, Spock_](https://bigbangtheory.fandom.com/wiki/Rock,_Paper,_Scissors,_Lizard,_Spock)?
      Modify your game to allow the extra options!
- [x] Have fun with the CSS by adding colors, animations, and effects to make the
      game more enjoyable

### Part 3

- [ ] Find at least THREE codewar you have not completed from our daily warmups and complete them. If you don't have THREE incomplete codewar warmups, find some new ones to tackle. I encourage for those who want an extra level of challenge, just let me know which codewar you are solving.
- [ ] For each, copy your solution into a gist:  See https://gist.gitub.com and include those links in your homework comment.

### Adventure Mode

- [ ] Your game is currently only 1 vs 1, add the ability to add more computer or users players to the game

**Comment by AbtaheeAli** [comment]
https://github.com/AbtaheeAli/roshambo

**Comment by AbtaheeAli** [comment]
`namespace Solution 
{
  public static class SpacesRemover
  {
    public static string NoSpace(string input)
    {
      return input.Replace(" ", "");
    }  
  }
}`

Gist kept timing out on me. No idea why

**Comment by AbtaheeAli** [comment]
`namespace Solution
{
  public static class Program
  {
    public static string repeatStr(int n, string s)
    {
            var str = "";
            for (int index = 0; index < n; index++)
            {
                str += s;
            }
            return str;
    }
  }
}`

**Comment by AbtaheeAli** [comment]
`public static class Kata
    {
         public static string Greet(string language)
        {
            switch (language.ToLower())
            {
                case "english":
                    return "Welcome";
                case "czech":
                    return "Vitejte";                
                case "danish":
                    return "Velkomst";
                case "dutch":
                    return "Welkom";                
                case "estonian":
                    return "Tere tulemast";                
                case "finnish":
                    return "Tervetuloa";                
                case "flemish":
                    return "Welgekomen";                
                case "french":
                    return "Bienvenue";                
                case "german":
                    return "Willkommen";                
                case "irish":
                    return "Failte";                
                case "italian":
                    return "Benvenuto";               
                case "latvian":
                    return "Gaidits";                
                case "lithuanian":
                    return "Laukiamas";                
                case "polish":
                    return "Witamy";                
                case "spanish":
                    return "Bienvenido";                
                case "swedish":
                    return "Valkommen";                
                case "welsh":
                    return "Croeso";
                default:
                    return "Welcome";
             }
          }
    }`

definitely took the long route for this one but it works!

**Comment by AbtaheeAli** [comment]
Your homework **06 - 04 - Roshambo!** was marked: **Meets Expectations**


![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9ab12a6cb8616834a8b7e838629a5c8c61b5f7a3/giphy-14.gif)
> &ldquo;Well done!&rdquo;
